CREATE OR REPLACE TABLE REPORT_METADATA
(
REPORT_ID NUMBER,
REPORT_NAME STRING,
TARGET_TABLE STRING,
QUERY STRING,
ACTIVE_FLAG STRING
);

INSERT INTO REPORT_METADATA VALUES
(
1,
'EMPLOYEE_SUMMARY',
'EMPLOYEE_OUTPUT',
'SELECT * FROM EMPLOYEE_MASTER',
'Y'
);

INSERT INTO REPORT_METADATA VALUES
(
2,
'ABSENCE_REPORT',
'ABSENCE_OUTPUT',
'SELECT * FROM ABSENCE_DETAILS',
'Y'
);